### ISSUE TITLE
Make paths relative

### ISSUE THREAD

**Issue by dpliakos** [DimitrisPl/studentBranchMeetings#5]
Some of the paths are in absolute path format. For that reason they wont work at if files are placed at a server's sub folders. Maybe it's better to be relative paths.
The reason that paths are in absolute path format is that index.php is using different paths than the other pages.

The paths file is under /includes/paths.php

**Comment by AlexanderTheGr8-gr** [comment]
The new path system (implemented in the last pull request) goes like this.
All paths are defined in "includes/filenames_and_paths.php".
Every file includes it once, and then to include a file you like you just do so by FILENAME_FILE or CONSTANTNAME_FILE. Therefor everyone of us must configure it (once in the future, again and again now xD) and every file can locate all the others with constants.
I think this is closed for now.
