### ISSUE TITLE
Remake the Database

### ISSUE THREAD

**Issue by dpliakos** [DimitrisPl/studentBranchMeetings#7]
Remake the database following the google doc's instructions.

See Google doc SQL section
 [Google doc here](https://docs.google.com/document/d/1bpWZoxktCWyrakaDsJ6gy_vURAPK6I7Y0MrxxEQi2Fo/edit)

**Comment by AlexanderTheGr8-gr** [comment]
I believe this issue is closed! :P

[install_database.txt](https://github.com/dPliakos/studentBranchMeetings/files/1033985/install_database.txt)
